### ISSUE TITLE
0x version 401 does not support --gen flag

### ISSUE THREAD

**Issue by WaikiSin2016** [davidmarkclements/0x#109]
Hi, I use 0x to generate flamegraphs. with v3 0x, I can generate graph with stacks.out file using --gen flag but with v401, the flag is not supported or available. 

thanks

Waiki at Lifion by ADP.

**Comment by davidmarkclements** [comment]
in v4 use --visualize-only

As long as you pass it a folder that contains a stacks.pid.out file (in your case pid can be any number) it should visualize it for you.

I'd encourage you to adopt 0x v4 for tracing instead of your current method. It uses a new approach to capturing stack traces which doesn't require sudo or privileged containers. This new approach resolves a missing functions problem in node 8.5.0+ due to turbofan's handling of unoptimized functions (they're not available  to kernel tracing tools).
