### ISSUE TITLE
Windows 10: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by StarpTech** [davidmarkclements/0x#111]
All programs are closed.

Node: 8.9.0
OS: Windows 10
```
Profilingserver listening on 3000
Process exited, generating flamegraph
EBUSY: resource busy or locked, rename 'E:\Repositorys\test\isolate-00000186A9961380-13812-v8.log' -> 'E:\Repositorys\test\13812.0x\isolate-00000186A9961380-13812-v8.log'
Terminate batch job (Y/N)?
```

Conclusion: Flame graph isn't generated.

**Comment by StarpTech** [comment]
The reason is the windows firewall. You have to disable "real-time protection" 😈

**Comment by davidmarkclements** [comment]
I think we need to document this, 
or find a work around

**Comment by StarpTech** [comment]
The workaround is to whitelist your repository.
![image](https://user-images.githubusercontent.com/1764424/37880079-4d0f6d48-3083-11e8-9959-a2c73453152a.png)

**Comment by mcollina** [comment]
This should probably go in the README.
Il giorno dom 25 mar 2018 alle 23:22 Dustin Deus <notifications@github.com>
ha scritto:

**Comment by davidmarkclements** [comment]
first I'd like to see if it can be worked around (for instance, maybe we can copy and then delete instead of move)

**Comment by davidmarkclements** [comment]
ok yep I have a way around it. 

V8 ticks can be written to stdout (`--prof --no-logfile-per-isolate --logfile=-`)
The user stdout of the node process is already redirected to a different fd because we process `--print-opt-source` on the actual stdout. The logfile and opt source output can be split with pattern matching (we know exactly what to look for, and it won't be accidentally mimicked because user stdout is to different fd). This can then be piped to a file in the profile folder, and Windows won't complain. Also keeps things tidier (no isolate log file in cwd, that might be left behind on failure etc).

**Comment by davidmarkclements** [comment]
ok not so easy, because we're getting `--print-opt-source` output as well, the output of both can merge together, making it very difficult to parse 

like so: 

```
--- FUNCTION SOURCtick,0x7fff9228e516,1463984,0,0x7fff921d9201,2,0x1007d91b0,0x339890c23812,0x339890addc6d,0x13f390b4cf54,0x13f390b4c4a4,0x13f390b4bf6c,0x13f390b4b122,0x13f390b4a874,0x339890c1eb96,0x13f390b43191,0x13f390b42e1b,0x13f390b42b89,0x13f390b4229e,0x13f3f7911251,0x339890c19a9c,0x339890c42bb9,0x339890c36539
E (_http_common.js:checkIsHttpToken) id{55,3} start{8959} ---
```

might have to go back to create a doc for Windows 10 work around for now

**Comment by mcollina** [comment]
This was fixed.
