### ISSUE TITLE
Improve performance on big graphs

### ISSUE THREAD

**Issue by mourner** [davidmarkclements/0x#113]
When generating a graph for an app that does a lot of stuff, there are so many entries in the graph that the browser simply can't handle it, leading to the UI completely freezing for 10–20 seconds on every click:

![image](https://user-images.githubusercontent.com/25395/38029325-38cc8cae-329e-11e8-8ec2-c1266a93892c.png)

Would it be possible to add an option to not include the smaller items (below a certain threshold, e.g. 0.1%) to make 0x usable on cases like this? 

Or is there another way of dealing with the performance? Maybe it's so slow because of the SVG nature of the chart (that breaks down on so many elements), and switching to simple HTML divs (that can be hardware-accelerated) would improve things?

cc @davidmarkclements

**Comment by davidmarkclements** [comment]
hi @mourner - yes this has been a known issue for a long time

switching to HTML divs wouldn't help, browsers get *very slow* past a certain threshold of html divs,
(it may actually be the html divs which contain text overlays for the svgs causing a lot of the issues)

essentially we need to rewrite the visualization engine, it's currently on an old version of d3 (which requires a hack which uses duplicate dummy element, doubling the problem) 

the chrome devtools they optimize in an interesting way where many small shapes are drawn as a single vector until a user interacts

long and short of it, there's a lot of work that needs to be done here, and getting around the bytecode handler problem by moving to the profiler instead of dtrace/perf by default took priority

**Comment by mourner** [comment]
@davidmarkclements I see, makes sense! Looks like https://github.com/ChromeDevTools/timeline-viewer is using Canvas to draw the flame chart. I'd be interested in looking into this — seems like there's a demand for a very fast generic flame chart library that can handle a million entries.

**Comment by mcollina** [comment]
@mourner that would be fantastic!

**Comment by mourner** [comment]
Heads up that I've built https://github.com/mapbox/flamebearer to address my profiling needs. It's much more minimalistic than 0x and has some different design choices, but hopefully you can borrow some performance tricks from it.

**Comment by davidmarkclements** [comment]
@mourner that's *awesome*! I def. want to focus on UI perf moving forward

**Comment by mcollina** [comment]
This is fixed in 4.1.0.
