### ISSUE TITLE
Testing v8 version different from logging version

### ISSUE THREAD

**Issue by BridgeAR** [davidmarkclements/0x#119]
When trying to use Node.js master I always get the an error without the possibility of getting a flamegraph.

```
0x -o -- ./out/Release/node test.js
// ...
// 🚫  Testing v8 version different from logging version
```

Trying to circumvent the issue by first only collecting the information and then to generate the flamegraph from that results in a different error:

```
0x --collect-only -- ./out/Release/node t.js
0x --visualize-only ./folder.0x
// 🔥  Profiling
// 🚫  Target subprocess error, code: 9
```

**Comment by davidmarkclements** [comment]
this is a problem with Node master

the V8 version reported by `process.versions.v8` and the v8 version in the log file header 
are different

you can work around it by changing the log file header to the version reported by `process.versions.v8`

came across this problem a while, checked again and it had been fixed in Node master, and now it's seems to be back again

**Comment by BridgeAR** [comment]
I am not sure in what way this is broken in Node core. I guess you mean e.g., `'6.6.346.24-node.5'` instead of `'6.6.346.24'`?

That is not a bug but a feature. We add extra patches to Node.js on top of the regular V8 version and should not change the original version at all. That is only done in case we pull in a new V8 version. I guess that is also what happened in the moment you checked and found that it was `fixed`.

**Comment by paambaati** [comment]
Is this possible? I'm trying to profile worker threads' performance on the latest master (`v11.0.0-pre`), and `0x` won't generate flamegraphs.

**Comment by BridgeAR** [comment]
Ping @davidmarkclements. I am running into this again as I would like to use 0x for Node core master.
