### ISSUE TITLE
Attaching 0x in the middle of the processing

### ISSUE THREAD

**Issue by behrad** [davidmarkclements/0x#129]
I want to start profiling with an interrupt or delay. Any options available?

**Comment by mcollina** [comment]
in which operating system/node version?

It might be possible on Linux or Solaris using kernel tracing (perf/dtrace). I'm not sure if this is supported in `0x`.

**Comment by behrad** [comment]
> in which operating system/node version?

CentOS 7, node v8.11.x

**Comment by spalger** [comment]
I also would really benefit from being able to run this on a subset of a process, even if I can't attach to the process while it's running the ability to start and stop the collection within the lifecycle of the program would be awesome. Running on the latest macOS and node here.

**Comment by davidmarkclements** [comment]
This is an advanced use case, you'll need attach perf or dtrace to the the process, generate stack output and then pass the stack output to 0x – all of this needs documenting though

**Comment by mannypamintuan** [comment]
I am interested in this advanced use case.

Specifically, the ability to begin/start profiling with a function call (`start()`) and end profiling without the `soft exit`.
My specific use-case is to have a web app with  endpoints that allow the start and end of profiling to occur, retrieve the `.0x` files and generate flamegraphs locally.

I believe this is related to the original issue. (if not, I'd be happy to make separate :) )

@davidmarkclements 
I'd like to help on this if possible. 
I am relatively new to node.js and so if this issue is not suited for a `first time contributor` I'd love to help in any other way.

**Comment by cc-ebay** [comment]
I would like to have this too. 
I would like to delay the profiling **after** a startup phase. 
It may be implemented listening for a signal, or a key or a programmatic function (ex: `require('0x').start()`
