### ISSUE TITLE
Init function filtering 

### ISSUE THREAD

**Issue by davidmarkclements** [davidmarkclements/0x#144]
Frames that are part of the initialisation process (e.g. module loading) are not being filtered/hidden behind the init button for data capture in node 10

**Comment by BridgeAR** [comment]
I ran some tests to see what types V8 returns and the INIT type is not there since Node.js 9.

```
Node.js 10:
* [CPP]
* [CODE:Builtin]
* [CODE:BytecodeHandler]
* [SHARED_LIB]
* [INLINABLE]
* [CODE:RegExp]
* [CODE:Stub]
* [eval]

Node.js 9:
* [CPP]
* [CODE:Stub]
* [CODE:KeyedStoreIC]
* [CODE:BytecodeHandler]
* [CODE:Builtin]
* [INLINABLE]
* [CODE:KeyedLoadIC]
* [CODE:RegExp]
* [CODE:LoadIC]
* [SHARED_LIB]

Node.js 8:
* [INIT]
* [CPP]
* [CODE:Stub]
* [INLINABLE]
* [CODE:Builtin]
* [CODE:BytecodeHandler]
* [CODE:Handler]
* [CODE:LoadIC]
* [CODE:KeyedLoadIC]
* [CODE:RegExp]
* [SHARED_LIB]
```

Looking at it closer, I see that the initialization detection in 8 was not bad. However, it did not detect all bootstrap code as INIT.

We could talk to the V8 team about specific types and our needs.

Since they are somewhat related, I combine this issue with #142. When I originally thought about the C++ code I did not expect the V8 code internals to be listed as such. But that is currently mostly the case.

I suggest to either add a new category that would only show user C++ code as that's more intuitive. From V8 perspective it makes sense that their C++ code shows up as such and that only the pure CSA functions show up as builtin.

In general the detection for our grouping function seems off and needs a closer look. Defining everything correct is the difficult part. I'll further investigate and check this with different input as well.

Shall we ask the V8 team about specific groups / more details in some cases? If yes, which ones?

// cc @mcollina

**Comment by mcollina** [comment]
@BridgeAR can we use some instrumentation that we add to the process instead? Specifically, can we stick something with `-r` to know that we are starting to load our app?

What is currently tagged as init?

**Comment by BridgeAR** [comment]
I guess that should be possible. I'll give it a try. Mostly module loading and bootstrapping is marked as such.
