### ISSUE TITLE
Why does 0x abort when the child process exits non-zero?

### ISSUE THREAD

**Issue by Qix-** [davidmarkclements/0x#181]
There doesn't seem to be a way to disable this either.

The application's behavior should be independent of 0x showing flamegraphs. Perhaps output that the application exited non-zero but that's no reason to not show a flamegraph.

For example, I'm profiling `xo` on certain scripts that might take a long time to generate results, in which case `xo` always exits non-zero. There's no reason 0x should abort generating a flamegraph.

**Comment by Qix-** [comment]
Right, I understand that. I'm asking why exit codes are honored at all, though - notwithstanding an optional flag.

**Comment by ovhemert** [comment]
@qix : I had the same issue and wanted my program to exit with `process.exit(1)` explicitly.
Since there were more issues regarding this, I've updated flame, bubble and doctor to change default behaviour and still collect data after child process terminates.

Changes have been merged into PR #199 

Does that close this issue for you?

**Comment by Qix-** [comment]
Yes :D it does, thank you.
