### ISSUE TITLE
discuss: flamegraphs on windows

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [davidmarkclements/0x#22]
I am opening this to discuss a possible integration of windows flame graphs and to collect some initial reading on it.

After a quick research a good starting point could be this:
- [xperf wrapping](https://github.com/MSOpenTech/ETWFlamegraph) (npm package by MS)
- [xperf](https://msdn.microsoft.com/en-us/library/windows/hardware/hh162920.aspx)

**Comment by davidmarkclements** [comment]
Yes this definitely should get some attention, great find on the etl conversion repo

**Comment by davidmarkclements** [comment]
just adding some notes

default sample rate is 1ms - https://msdn.microsoft.com/en-us/library/windows/hardware/hh162977.aspx --setprofint , default 10000ns === 1ms - this in 0x we profile per 1ms for perf and dtrace (because dtrace limit is 1ms) 

would setting -clocktype to Cycle be more consistent with dtrace/perf (and does it matter?)

getting way too much info in the output (large files, long parse times) - it's unclear how we *just* get info for a single node process (particularly if we want related C methods and syscalls). Either way `-on Latency` is tmi. 

would `-pids` flag help - docs tend to suggest not 

--- 
we'll need to add setup instructions doc for windows, 

windows vista, 7, 8 will need https://www.microsoft.com/en-gb/download/details.aspx?id=39982 to get xperf

windows 10 will need  https://msdn.microsoft.com/en-us/windows/hardware/dn913721.aspx

---

we'll need to check for 64bit systems, and if so run following reg alteration

```
REG ADD "HKLM\System\CurrentControlSet\Control\Session Manager\Memory Management" -v DisablePagingExecutive -d 0x1 -t REG_DWORD -f
```
---
I had to manually retrieve and load the NodeJS-ETW-provider manifest, this could be different for each node version

<https://github.com/nodejs/node/blob/master/src/res/node_etw_provider.man>

could be a headache to manage

---

xperf needs admin rights, hopefully we can follow the same pattern in 0x as used for dtrace and perf (ask for pw to allow for sudo) using `runas` : 

```sh
runas /noprofile /user:Administrator xperf
```
may also be a headache to get right

there's also elevate (<http://code.kliu.org/misc/elevate/>) - which we could package into a sep. node module 

---

we may be able to bypass all of this with powershell Get Win-Event (https://blogs.technet.microsoft.com/heyscriptingguy/2011/01/24/use-powershell-cmdlet-to-filter-event-log-for-easy-parsing/) and this node wrapper - <https://www.npmjs.com/package/windows-eventlog-reader> - however this may we *only* get JS stacks but ... maybe not

**Comment by davidmarkclements** [comment]
now.. I guess the question is.. do we *just* support windows 10 via the linux subsystem they're bundling with it (and therefore avoid all of the work), or do we support legacy windows? To decide this we need to know

1) will windows 10 be the dominant production server environment?
2) does the windows 10 subsystem have perf-events? 
3) what's the current usage of windows versions today (both desktop and server)?
4) what's the predicted usage of windows versions in the future (both desktop and server)?

@piccoloaiutante would you have insight here? what's your thoughts - should we support windows vista and up in 0x or should we just wait for windows 10 to take over?

**Comment by piccoloaiutante** [comment]
I'm currently downloading the latest Win 10 beta with the first preview of the Linux subsystem. We could make a quick lap around it to have the grasp of what to expect. I would avoid supporting Windows Vista. The standard now is supporting from windows 7. I saw this week that Win 10 is now around 17% of the window installed machines (here few info http://www.w3schools.com/browsers/browsers_os.asp)

On the long running yes windows 10 is going to take the role of win7 and win8. I'm still trying to get statistics for windows server. I'll be back to you as soon as possible.

**Comment by davidmarkclements** [comment]
@piccoloaiutante - did you get any where running 0x on win 10?

**Comment by piccoloaiutante** [comment]
@davidmarkclements I successfully installed it on Bash in Win 10 but then i run into this problem:

https://github.com/npm/npm/issues/12445

It seems that it is still too early to think about running node on Win10 Bash.

![screen shot 2016-06-17 at 12 54 36](https://cloud.githubusercontent.com/assets/867842/16148562/b49aeb00-348a-11e6-86d6-1d2154722091.png)

**Comment by davidmarkclements** [comment]
is `perf` installed (or even possible to install) on win?

**Comment by piccoloaiutante** [comment]
it wasn't. I've tried to install it as part of `linux-tools` but it seems not a part of them.

Any idea on how to get it?

Consider that `linux-tools-3.4.0+` doesn't exist in apt repo..


![screen shot 2016-06-17 at 13 33 48](https://cloud.githubusercontent.com/assets/867842/16149328/5383afae-3490-11e6-9a92-11dcc5297780.png)

**Comment by davidmarkclements** [comment]
so there's two sides, theres the user space `perf` and then there's having `perf` compiled into the kernel. 

if the user space perf doesn't match kernel version then user space perf won't work, 
also if it's a custom kernel version, then we're stuck

There's the same problem with docker containers on OS X (custom kernel)  
(see https://github.com/davidmarkclements/0x/pull/9) 

Actually, it may be interesting to see if the new docker for windows (and mac) has a kernel with perf, then at least we can make this work in a container on windows

**Comment by mcollina** [comment]
All roads points to ETW: https://msdn.microsoft.com/en-us/library/windows/desktop/bb968803(v=vs.85).aspx

cc @nebrius

**Comment by mcollina** [comment]
This should be key to get this done: https://blogs.msdn.microsoft.com/interoperability/2012/12/03/ms-open-tech-contributes-support-for-windows-etw-and-perf-counters-to-node-js/

**Comment by shockwavemoto** [comment]
now.. I guess the question is.. do we just support windows 10 via the linux subsystem they're bundling with it (and therefore avoid all of the work), or do we support legacy windows? To decide this we need to know

will windows 10 be the dominant production server environment?
does the windows 10 subsystem have perf-events?
what's the current usage of windows versions today (both desktop and server)?
what's the predicted usage of windows versions in the future (both desktop and server)?
would you have insight here? what's your thoughts - should we support windows vista and up in 0x or should we just wait for windows 10 to take over?

**Comment by davidmarkclements** [comment]
now covered in v4
