### ISSUE TITLE
Avoid generating .__browserify_string_empty.js

### ISSUE THREAD

**Issue by mcollina** [davidmarkclements/0x#25]
As titled, running 0x anywhere create that files (which is empty) in the current folder.

**Comment by eljefedelrodeodeljefe** [comment]
Maybe it would be worth looking at storing all generated content into some output folder, namely the profiles... In order to clear them more easily later. 

Maybe looking for and storing to `os.tmpdir()`. If only the current PR for making temp dirs would be landed (and backported down to 0.12) :smile:

**Comment by davidmarkclements** [comment]
The empty file is a byproduct of browserify-string, its never populated, it's a dummy hack, because browserify needs a file. Fix coming shortly
