### ISSUE TITLE
flamegraph diffing

### ISSUE THREAD

**Issue by davidmarkclements** [davidmarkclements/0x#47]
- flamegraph of deltas ?
- overlay flamegraphs?

**Comment by mcollina** [comment]
This is quite a fascinating concept. Being able to check before and after a change, how the flamegraphs evolved. I'm not sure what the result would be.

**Comment by bengl** [comment]
It would be cool to flamegraph-ish visualization of the data that can be generated by `perf diff`, for example.

**Comment by davidmarkclements** [comment]
if we can apply the same idea encapsulated in `perf-diff` to diffing the itnermediate JSON trees that 0x generates we can be instantly cross platform

**Comment by davidmarkclements** [comment]
what I'm unsure about is how `perf diff` accounts for variations in sampling

due to the asynchronous nature of JS, stacks *may* be captured in different orders between profiling events - which is where diffing for *meaning* becomes the challenge

**Comment by bengl** [comment]
I like the approach taken here: https://github.com/brendangregg/FlameGraph/blob/master/difffolded.pl

I've used this tool to identify bottlenecks eliminated or introduced by code changes. It's pretty neat.

**Comment by davidmarkclements** [comment]
Wow. Ok yeah I think that's it. In this case the purple block represents a performance difference in that call frame?

**Comment by bengl** [comment]
Yeah so the white blocks have the same number of samples. The red ones indicate *more* samples in the second perf file, and the blue ones indicate *less* samples in the second perf file. I just wrote some simple nonsense code with some giant loops, changing the size of the loops for the second run.

**Comment by mcollina** [comment]
@bengl now I'm looking forward to it :D. Would you like to send a PR?

**Comment by shockwavemoto** [comment]
Yeah so the white blocks have the same number of samples. The red ones indicate more samples in the second perf file, and the blue ones indicate less samples in the second perf file. I just wrote some simple nonsense code with some giant loops, changing the size of the loops for the second run.what I'm unsure about is how perf diff accounts for variations in sampling

due to the asynchronous nature of JS, stacks may be captured in different orders between profiling events - which is where diffing for meaning becomes the challenge if we can apply the same idea encapsulated in perf-diff to diffing the intermediate JSON trees that 0x generates we can be instantly cross platform
