### ISSUE TITLE
Import the same data from the tick processor

### ISSUE THREAD

**Issue by mcollina** [davidmarkclements/0x#75]
Currently it's possible to use an internal visualization of v8

https://github.com/v8/v8/tree/master/tools/profview

but only if we preprocess things with:

https://github.com/v8/v8/blob/master/tools/linux-tick-processor

which requires a `d8` binary.

**Comment by davidmarkclements** [comment]
do we know if the `d8` binary has to match the v8 version exactly? Or is it good for minor range?

**Comment by mcollina** [comment]
I do not know. Building one of those is a major task, and I would recommend against automating it. Porting the tick processor (it's JS!) should be simpler.

**Comment by jaro-sevcik** [comment]
Regarding the question about `d8` that's necessary to run `linux-tick-processor`, it should not really matter.

However, does not `node` already run some for of tick processor with `node --prof-process`? It should not be hard to change that to produce the file for profview.

I also would not be opposed to changing the tick processor to work with both `d8` and `node` without a shim. I would actually prefer to run it with `node`.

(FYI, I wrote the `profview` tool.)

**Comment by davidmarkclements** [comment]
@jaro-sevcik yes I've been playing with that for a while - unfortunately my conclusion is that the paradigms from the tick processor don't map to the paradigms of stack collection

* in particular the "top of stack" concept we use to determine event loop blocking which in turn we translate the concept of "heat" (the redness of a block) doesn't seem to figure in the same way - the stacks are already pre-aggregated or something (maybe by prof-process, it's possible that they're not in raw form.. but I don't know, seems like they might be...)
* a "tick" can also (seemingly) include calls across ticks (in the `s` property of code references, you can observe a call to setTimeout followed by function calls from the callback handler) - so you can't use difference between timestamps (`tm`) in a given "stack" as an alternative weighting mechanism to determine "heat" - because the "stack" in the profiling case may also include asynchronous calls
* finally, the isolate files only relate to v8 activity so they won't capture native C libs outside of that world (such as process.bindings('fs'), or third party native C addon modules)

If I'm wrong on points I'd appreciate the correction, perhaps I'm missing something - in the meantime I'll close this issue (perhaps only for now)

**Comment by jaro-sevcik** [comment]
@davidmarkclements Thank you for your observations, could you possibly elaborate on the problems you are seeing? We can (and want to) make this better. If you can give us an example where things look wrong, it would be great.

* It is surprising that you see wrong top-of-stack. That's actually one of the few things we should be getting quite reliably. The stacks should not be pre-aggregated. The prof-process tool should only resolve addresses on stack to code objects or C++ symbols.

* Similarly, there should not be "calls across ticks", whatever that means. Tick should always be just one stack trace. We do not combine two points in time or two threads.

* As for C++ symbol resolution of third-party code, this is just a matter of plumbing - we are missing the `shared-library` entries in the `isolate-*.log` log file. If we managed to get those in there before prof-process runs (either by adding them hackily to the log file, or by introducing some API to do that via v8), it should work.

The bigger problem is that the built-in tick sampler does not really understand the C stacks. It does understand the concept of top-of-stack and it should know through which point it entered the C land (if it entered via a runtime call), but it cannot walk the stack frames in-between. I suppose that is the show-stopper for you?

BTW, I am also responsible for the Linux perf tool integration, if you have any feedback on that, it would be very welcome.

**Comment by davidmarkclements** [comment]
@jaro-sevcik thanks!


* re top of stack.. ok interesting I'll have to dig deeper on this and come back
* time allowing, I'll try to put together an isolated example demonstration case and come back to you on the "calls across ticks" (asynchronous call graphs) 
* that would be *very* cool - if we had that an a way to interpret we could simplify the implementation of 0x significantly across platforms, get windows support, without losing any stack data
