### ISSUE TITLE
new cli syntax 

### ISSUE THREAD

**Issue by davidmarkclements** [davidmarkclements/0x#84]
the previous CLI syntax was difficult to maintain `0x [0xflags] node [nodeflags] [script] [scriptflags]`, and so was removed

current CLI syntax `0x [0xflags] --node-options=[nodeflags] [script] [scriptflags]` isn't ideal/conventional especially when it comes to integration with other tools

solution is to follow the `--` convention, e.g. `0x [0xflags] -- node [nodeflags] [script] [scriptflags]`
with a convenience fallback of `0x [0xflags] [script] [scriptflags]`

For backwards compat we could keep `--node-options` as well 

cc @mcollina @AndreasMadsen

**Comment by AndreasMadsen** [comment]
I tried the convenience fallback, it is quite difficult to make it work. Even worse, I think it teaches the wrong pattern. It is better to just enforce the correct pattern from the beginning, then there is no ambiguity.

**Comment by davidmarkclements** [comment]
you might be right. 

however, if we remove it, it's a fundamentally breaking change, it will be ergonomically jarring for any current users

**Comment by mcollina** [comment]
Some notes:

1. the current code architecture needs a __huge__ refactoring, specifically because the CLI and the generation phase are not separated, e.g. https://github.com/davidmarkclements/0x/blob/master/index.js#L18 and the main integration function is missing a callback.
2. the current CLI tool is hardly ergonomic, however it has some benefits on the lowest number of chars the user needs to type
3. the current codebase prevent anyone developing an alternative CLI for this
4. it is not clear which files are used in the browser and which file are for the CLI

**Comment by mcollina** [comment]
I'm 👍  with doing a huge refactoring, but I will keep the current cli tool as is for the moment.

**Comment by davidmarkclements** [comment]
Closed with v3
